services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: userstudy
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      # 경로 끝에 반드시 파일명까지 적혀있어야 합니다!
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # 컨테이너 환경에서는 localhost가 아닌 서비스 이름 'db'로 접속해야 합니다.
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userstudy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      # JPA가 테이블을 새로 만들지 않고 init.sql의 내용을 사용하도록 설정
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate