spring.application.name=userstudy

# 1. DB 연결 설정 (도커 서비스명 'db'를 사용)
# spring.datasource.url=jdbc:mysql://db:3306/userstudy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://db:3306/userstudy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234


# 2. JPA/Hibernate 설정
# 이미 init.sql로 테이블을 만들었으므로 검증(none 또는 validate)만 수행합니다.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. 롬복 설정 (로그 확인용)
logging.level.org.hibernate.SQL=DEBUG